[build]
  command = "npm install && npm run build --workspace=client"
  publish = "client/dist"

[build.environment]
  NODE_VERSION = "20"
  NETLIFY_BUILD_CACHE_INVALIDATE = "2026-06-19-v3"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"